<template>
  <div class="bg-gray-100 text-gray-800 darkMode">
    <div class="max-w-screen-md m-auto py-9">
        <h1 class="">Privacy Notice</h1>
        <p>Protecting your privacy is important to NCATS. This website links to other National Institutes of Health (NIH) sites, federal agency sites and private organization sites. Once you leave the primary ncats.nih.gov website, you are subject to the privacy policy for the site(s) you visit. NCATS does not collect any personally identifiable information (PII) about you during your visit to this site unless you choose to provide it. NCATS does, however, collect some data about your visit to better understand how the public uses the site and how to make it more helpful. NCATS collects information from visitors who read, browse and/or download information from this site. NCATS never collects information for commercial marketing or any purpose unrelated to the Center’s mission and goals.</p>

        <p>When visitors send email messages containing personal information to the general ncats.nih.gov email box&nbsp;<a href="mailto:info@ncats.nih.gov" class="mailto">info@ncats.nih.gov<span class="mailto"><span class="element-invisible"> (link sends e-mail)</span></span></a>, NCATS responds to and files the messages. Only designated staff and contractors requiring access to the emails to respond may view or answer them.</p>

        <h2>Types of Information Collected</h2>

        <p>When you browse through any website, certain information about your visit can be collected. NCATS automatically collects and temporarily stores the following type of information about your visit:</p>

        <ul>
            <li>Domain from which you access the Internet.</li>
            <li>IP address (an IP address is a number that is automatically assigned to a computer when surfing the Web).</li>
            <li>Operating system and information about the browser used when visiting the site.</li>
            <li>Date and time of your visit.</li>
            <li>Pages you visited.</li>
            <li>Address of the website that connected you to NCATS (such as google.com or bing.com).</li>
        </ul>

        <p>NCATS uses this information to measure the number of visitors to our site and its various sections and to help make our site more useful to visitors.</p>

        <h2>How NCATS Collects Information</h2>

        <p>This website uses Google Analytics measurement software to collect the information in the bulleted list under&nbsp;<em>Types of Information Collected</em>. Google Analytics collect information automatically and continuously. No PII is collected. NCATS staff and contractors conduct analyses and report on the aggregated data from Google Analytics. The reports are only available to this website’s managers and other designated staff who require this information to perform their duties. NCATS retains the data from Google Analytics as long as needed to support the mission of this website.</p>

        <h2>How NCATS Uses Cookies</h2>

        <p>The Office of Management and Budget (OMB) memo&nbsp;<a href="https://www.digitalgov.gov/resources/m-10-22-guidance-for-online-use-of-web-measurement-and-customization-technologies/" target="_blank">M-10-22, Guidance for Online Use of Web Measurement and Customization Technologies</a>&nbsp;allows federal agencies to use session and persistent cookies.</p>

        <p>When you visit any website, its server may generate a piece of text known as a “cookie” to place on your computer. The cookie allows the server to “remember” specific information about your visit while you are connected.</p>

        <p>The cookie makes it easier for you to use the dynamic features of Web pages. Cookies from NCATS Web pages only collect information about your browser’s visit to the site; they do not collect personal information about you.</p>

        <p>There are two types of cookies, single session (temporary) and multi-session (persistent). Session cookies last only as long as your Web browser is open. Once you close your browser, the cookie disappears. Persistent cookies are stored on your computer for longer periods.</p>

        <p><strong>Session Cookies:</strong>&nbsp;We use session cookies for technical purposes, such as to enable better navigation through our site. These cookies let our server know that you are continuing a visit to our site. The OMB memo 10-22 guidance defines use of session cookies as "Usage Tier 1—Single Session.” The policy says, “This tier encompasses any use of single session Web measurement and customization technologies.”</p>

        <p><strong>Persistent Cookies:</strong>&nbsp;We use persistent cookies to enable Google Analytics to differentiate between new and returning ncats.nih.gov visitors. Persistent cookies remain on your computer between visits to this website until they expire. The OMB memo 10-22 guidance defines use of persistent cookies as "Usage Tier 2—Multi-session without Personally Identifiable Information (PII).” The policy says, “This tier encompasses any use of multi-session Web measurement and customization technologies when no PII is collected.”</p>

        <p><strong>Opt Out or Disable Cookies:</strong> If you do not wish to have session or persistent cookies placed on your computer, you can disable them using your Web browser. If you opt out of cookies, you will still have access to all information and resources at ncats.nih.gov. Find <a href="http://www.usa.gov/optout_instructions.shtml" target="_blank">instructions for disabling or opting out of cookies</a> in the most popular browsers. <strong><em>Note:</em></strong> By following the instructions to opt-out of cookies, you will disable cookies from all sources, not just those from ncats.nih.gov.</p>

        <h2>How Personal Information is Protected</h2>

        <p>You do not have to give NCATS personal information to visit this website. However, if you choose to receive announcements or e-newsletters, NCATS collects your email address to complete the subscription process.</p>

        <p>If you choose to provide PII (information that is personal in nature and which may be used to identify you) through an email message, request for information, paper or electronic form, questionnaire, epidemiology research study, etc., NCATS will maintain the information you provide only as long as needed to respond to your question or to fulfill the stated purpose of the communication. If NCATS stores your personal information in a record system designed to retrieve information about you by personal identifier (name, personal email address, home mailing address, personal or mobile phone number, etc.), so that NCATS can contact you, the Center will safeguard the information you provide in accordance with the Privacy Act of 1974, as amended (5 U.S.C. Section 552a).</p>

        <p>NCATS operates a record system designed to retrieve information about you in order to accomplish its mission, so a Privacy Act Notification Statement (this policy) is displayed on the public-facing website. The notice addresses the following five criteria:</p>

        <ul>
            <li>NCATS legal authorization to collect information about you</li>
            <li>Purpose of the information collection</li>
            <li>Routine uses for disclosure of information outside of NCATS</li>
            <li>Whether the request made of you is voluntary or mandatory under law</li>
            <li>Effects of non-disclosure if you choose to not provide the requested information</li>
        </ul>

        <p>For further information about privacy at NIH, email the <a href="mailto:privacy@mail.nih.gov" class="mailto">NIH Senior Official for Privacy<span class="mailto"><span class="element-invisible"> (link sends e-mail)</span></span></a>, call 301-451-3426 or visit&nbsp;the <a href="https://oma.od.nih.gov/DMS/Pages/Privacy-Program.aspx" target="_blank" title="NIH Office of Management Assessment - Privacy Program">NIH Office of Management Assessment</a>.</p>

        <h2>Data Safeguarding and Privacy</h2>

        <p>NCATS uses Web measurement and customization technologies to help sites function better for visitors and to better understand how the public uses NCATS’ online resources. All uses of Web-based technologies comply with existing policies with respect to privacy and data safeguarding standards. Information Technology (IT) systems owned and operated by NCATS are assessed using Privacy Impact Assessments (PIAs) posted for public view on the Department of Health and Human Services (DHHS) <a href="http://www.hhs.gov/pia/" target="_blank">Privacy Impact Assessments</a> Web page. NCATS conducts and publishes a PIA for each use of a third-party website and application (TPWA) as they may have a different functionality or practice. TPWA PIAs are posted for public view on the DHHS website.</p>

        <p>When Web measurement and customization technologies are used, a Privacy Notice displayed on the website must provide:</p>

        <ul>
            <li>Purpose of the web measurement and/or customization technology.</li>
            <li>Usage tier, session type, and technology used.</li>
            <li>Nature of the information collected.</li>
            <li>Purpose and use of the information.</li>
            <li>Whether and to whom the information will be disclosed.</li>
            <li>Privacy safeguards applied to the information.</li>
            <li>Data retention policy for the information.</li>
            <li>Whether the technology is enabled by default or not and why.</li>
            <li>How to opt-out of the Web measurement/customization technology.</li>
            <li>Statement that opting-out still permits users to access comparable information or services.</li>
            <li>Identities of all third-party vendors involved in the measurement and customization process.</li>
        </ul>

        <h2>Data Retention and Access Limits</h2>

        <p>NCATS will retain collected data long enough to achieve the specified objective for which they were collected. The data generated from these activities falls under the National Archives and Records Administration (NARA) <a href="https://www.archives.gov/records-mgmt/grs.html" target="_blank">General Records Schedule (GRS)</a> and will be handled per the requirements of that schedule.</p>

        <h2>How NCATS Uses Third-Party Websites and Applications</h2>

        <p>As part of OMB memo&nbsp;<a href="https://obamawhitehouse.archives.gov/open/documents/open-government-directive" target="_blank">M-10-06, Open Government Directive</a>, NCATS uses a variety of new technologies and social media options to communicate and interact with citizens. These sites and applications include popular social networking and media sites, open source software communities and more. TPWAs are Web-based technologies that are not exclusively operated or controlled by NCATS, such as applications not hosted on a.gov domain or those that are embedded on NCATS Web pages. Users of TPWAs often share information with the general public, user community, and/or the third-party operating the website. These actors may use this information in a variety of ways. TPWAs could cause PII to become available or accessible to NCATS and the public, regardless of whether the information is explicitly solicited or collected by NCATS.</p>

        <p>The following list includes some of the TPWAs that NCATS uses and their purposes. NCATS sometimes collects and uses PII made available through third-party websites. However, we do not share PII made available through third-party websites. Your activity on the third-party websites NCATS uses is governed by the security and privacy policy of those sites (linked below). Review the third-party privacy policies before using the sites and ensure that you understand how your information may be used. If you have an account with a third-party website and choose to follow, like, friend, or comment, certain PII associated with your account may be made available to NCATS based on the privacy policy of the third-party website and your privacy settings within that third-party website. Therefore, you should also adjust privacy settings on your account to match your preferences.</p>

        <p>For any NCATS TPWA that collects PII, the list below also includes details on the information NCATS collects and how the Center protects your private information.</p>

        <h2>Third-Party Websites and Applications</h2>

        <p><strong><em>Bit.ly</em>:</strong>&nbsp;NCATS uses&nbsp;<em>Bit.ly</em>&nbsp;to shorten long URLs for use in email messages, in <em>Twitter</em>&nbsp;feeds, on&nbsp;<em>Facebook</em>&nbsp;pages, and in linking to media stories and funding opportunities.&nbsp;<em>Bit.ly</em>&nbsp;collects and provides data on how often you, as an email recipient or&nbsp;<em>Facebook/Twitter</em>&nbsp;user, click on the shortened URLs distributed by NCATS.&nbsp;<em>Bit.ly&nbsp;</em>analytics show how many people clicked on the URLs, compared to the total number of clicks on the shortened URLs.&nbsp;<em>Bit.ly</em>&nbsp;analytics do not provide any PII about the visitors who open the shortened links. Review the&nbsp;<a href="http://bit.ly/pages/privacy" class="ext" target="_blank"><em>Bit.ly</em>&nbsp;Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p><strong><em>Facebook</em>:</strong>&nbsp;NCATS has one main&nbsp;<em>Facebook&nbsp;</em>page: <a href="https://www.facebook.com/ncats.nih.gov" class="ext" target="_blank"><em>National Center for Advancing Translational Sciences</em><span class="ext"><span class="element-invisible"> (link is external)</span></span></a>. NCATS&nbsp;<em>Facebook</em>&nbsp;pages are managed by NCATS staff and contractors, who post news and other items of interest to be consumed by the public. If you have a&nbsp;<em>Facebook</em>&nbsp;account, you can log in to your account to post comments and “like” the NCATS<em>&nbsp;Facebook</em>&nbsp;page and individual entries. If, after you click on the NCATS&nbsp;<em>Facebook&nbsp;</em>page, you comment or click the “like” button, your PII will be visible to NCATS staff and other&nbsp;<em>Facebook</em>&nbsp;site visitors. The amount of visible personal information displayed will depend on your own&nbsp;<em>Facebook</em>&nbsp;privacy settings. You can completely avoid displaying any PII by not creating a&nbsp;<em>Facebook</em>&nbsp;account, not posting comments, not clicking on the “like” options, or not interacting with the NCATS<em>&nbsp;Facebook</em>&nbsp;account in any way (i.e., private messaging, sharing posts, etc.). NCATS staff and contractors do not collect, use or disclose any information about visitors who comment or “like” the NCATS <em>Facebook</em>&nbsp;page. However, as a practice, the <a href="https://ncats.nih.gov/comments">NCATS Comment Policy</a> requires the removal from the NCATS&nbsp;<em>Facebook</em>&nbsp;page of any comments that contain spam or are improper, inflammatory, off-topic or offensive. Repeat offenders may be subject to banning. The information is then saved on a password-protected shared drive accessible to designated staff who require this information to perform their duties. Review the&nbsp;<a href="http://www.facebook.com/policy.php" class="ext" target="_blank">Facebook&nbsp;Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p><strong><em>Flickr</em>:</strong>&nbsp;NCATS uses&nbsp;<em>Flickr</em>&nbsp;to upload and share photos and images related to the Center’s mission and culture. NCATS is responsible for the uploaded images on NCATS-sponsored&nbsp;<em>Flickr</em>&nbsp;pages and must ensure that the images assigned for posting meet quality standards and comply with all NIH, DHHS and federal policies. Images posted are produced by NCATS and may include medical illustrations and other scientific images. Photos posted may also include photos of NCATS employees at events or in labs for the purpose of promoting the Center’s mission and culture. You do not need to register with&nbsp;<em>Flickr</em>&nbsp;to view the images on NCATS&nbsp;<em>Flickr</em> pages because all NCATS images posted on&nbsp;<em>Flickr</em>&nbsp;are visible in the public domain. However, if you choose to register, you will not provide PII directly to NCATS. The Center has disabled the commenting feature on its&nbsp;<em>Flickr</em>&nbsp;pages. Therefore, PII cannot be collected or unintentionally received by NCATS via the&nbsp;<em>Flickr</em>&nbsp;site. Review the&nbsp;<a href="http://info.yahoo.com/privacy/us/yahoo/flickr/details.html" class="ext" target="_blank"><em>Flickr</em>&nbsp;Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p><strong><em>LinkedIn</em></strong><strong style="color: rgb(0, 0, 0);">:</strong><strong><em> </em></strong>NCATS has one main&nbsp;<em>LinkedIn </em>page: <em><a href="https://www.linkedin.com/company/nih-ncats/" target="_blank" title="National Center for Advancing Translational Sciences (NCATS): Overview - LinkedIn" class="ext">National Center for Advancing Translational Sciences<span class="ext"><span class="element-invisible"> (link is external)</span></span></a></em>. NCATS uses&nbsp;<em>LinkedIn</em>&nbsp;to post news and other items of interest and to respond to comments and inquiries sent to NCATS via&nbsp;<em>LinkedIn</em>. You may read the NCATS&nbsp;<em>LinkedIn</em>&nbsp;feeds without subscribing to them. If you want to subscribe to (or follow) NCATS&nbsp;<em>LinkedIn</em>&nbsp;feeds, you must create a&nbsp;<em>LinkedIn</em>&nbsp;account at&nbsp;<a href="http://www.linkedin.com/" target="_blank" title="LinkedIn" class="ext">www.linkedin.com<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>. To create an account, you must provide some personal information, such as your name, username, password and email address. You have the option to provide additional personal information, including a short work history, a location and a picture. Most information you provide for a&nbsp;<em>LinkedIn</em>&nbsp;account is available to the public, but you can modify how much of your information is visible by changing your privacy settings on&nbsp;<em>LinkedIn</em>.com. NCATS staff and contractors monitor the number of subscribers and respond to comments and queries via&nbsp;<em>LinkedIn</em>, but these individuals never take possession of the personal information belonging to you as a&nbsp;<em>LinkedIn</em> follower. However, as a practice, the NCATS Comment Policy requires the removal from the NCATS&nbsp;<em>LinkedIn</em>&nbsp;page of any comments that contain spam or are improper, inflammatory or offensive. The information is then saved on a password-protected shared drive accessible to designated staff who require this information to perform their duties. Review the <a href="https://www.linkedin.com/legal/privacy-policy?trk=uno-reg-guest-home-privacy-policy" target="_blank" title="Privacy Policy - LinkedIn" class="ext"><em>LinkedIn </em> Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p><strong><em>MailChimp Subscription Management</em>:</strong>&nbsp;NCATS uses&nbsp;<em>MailChimp</em>&nbsp;to send e-newsletters, announcements and other messages to users who subscribe to receive them. To subscribe to receive an NCATS product, you must provide an email address and indicate your subscription preferences, including the items you want to receive. The email subscriber lists are password protected by&nbsp;<em>MailChimp</em>. Only the NCATS managers who send newsletters, announcements or other communications via <em>MailChimp</em>&nbsp;and the staff and contractors who monitor the results of email initiatives have access to the subscriber lists.&nbsp;<em>MailChimp</em> never allows access to the subscriber lists to anyone outside of NCATS for any purpose. <em>MailChimp</em> collects and provides non-identifying information about the number of messages sent, clicks and open rates. This information is password-protected and only available to designated staff who require this information to perform their duties. Review the&nbsp;<a href="http://mailchimp.com/legal/privacy/" class="ext" target="_blank"><em>MailChimp</em> Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p><strong><em>Twitter</em>:</strong>&nbsp;NCATS has one main <em>Twitter</em> page: <a href="https://twitter.com/ncats_nih_gov" class="ext" target="_blank"><em>National Center for Advancing Translational Sciences</em><span class="ext"><span class="element-invisible"> (link is external)</span></span></a>&nbsp;<a href="http://www.ncats.nih.gov/about/disclaimer.html" target="_blank"> </a>. NCATS uses&nbsp;<em>Twitter</em>&nbsp;to send short messages or “tweets” (up to 140 characters) to share information about NCATS and respond to comments and inquiries sent via&nbsp;<em>Twitte</em>r to NCATS. You may read the NCATS&nbsp;<em>Twitter</em>&nbsp;feeds without subscribing to them. If you want to subscribe to (or follow) NCATS&nbsp;<em>Twitter</em>&nbsp;feeds, you must create a&nbsp;<em>Twitter</em>&nbsp;account at <a href="http://www.twitter.com" class="ext" target="_blank">www.twitter.com<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>. To create an account, you must provide some personal information, such as your name, user name, password and email address. You have the option to provide additional personal information, including a short biography, location or a picture. Most information you provide for a <em>Twitter</em>&nbsp;account is available to the public, but you can modify how much of your information is visible by changing your privacy settings on <em>Twitter</em>.com. NCATS staff and contractors monitor the number of subscribers and respond to comments and queries via&nbsp;<em>Twitte</em>r, but these individuals never take possession of the personal information belonging to you as a <em>Twitte</em>r follower. However, as a practice, the NCATS Comment Policy requires the removal from the NCATS&nbsp;<em>Twitter</em>&nbsp;page of any comments that contain spam or are improper, inflammatory or offensive. The information is then saved on a password-protected shared drive accessible to designated staff who require this information to perform their duties. Review the <a href="http://twitter.com/privacy" class="ext" target="_blank"><em>Twitter</em>&nbsp;Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p><strong><em>YouTube</em>:</strong>&nbsp;NCATS has one main YouTube channel: <a href="http://www.youtube.com/user/ncatsmedia" class="ext" target="_blank"><em>National Center for Advancing Translational Sciences</em><span class="ext"><span class="element-invisible"> (link is external)</span></span></a>&nbsp;<a href="http://www.ncats.nih.gov/about/disclaimer.html" target="_blank"> </a> <em>.</em> NCATS posts videos on&nbsp;<em>YouTube</em>&nbsp;to make them available to the public. You do not need to register with either&nbsp;<em>YouTube</em>&nbsp;or Google (which owns <em>YouTube</em>) to watch NCATS<em>&nbsp;YouTube</em>&nbsp;videos. When you watch videos,&nbsp;<em>YouTube</em> may record non-personally identifiable information about their site usage, such as channels used, videos watched, and data transfer details to improve its services. If you login to the&nbsp;<em>YouTube</em>&nbsp;site before watching NCATS videos,&nbsp;<em>YouTube</em>&nbsp;may associate information about your site usage with your <em>YouTube</em>&nbsp;account. If you login to&nbsp;<em>YouTube&nbsp;</em>and comment on an NCATS video, any personal information you included on your&nbsp;<em>YouTube</em>&nbsp;profile page will be visible to visitors who click on the comment field. If you do not log in before watching NCATS videos posted on&nbsp;<em>YouTub</em>e, you cannot comment on NCATS videos, and your site usage will not be associated with you or a&nbsp;<em>YouTube</em> account. Review the&nbsp;<a href="http://www.youtube.com/t/privacy" class="ext" target="_blank"><em>YouTube</em>&nbsp;Privacy Policy<span class="ext"><span class="element-invisible"> (link is external)</span></span></a>.</p>

        <p>For more information on the uses of social and new media for which the General Services Administration has negotiated a federally friendly Terms of Service agreement, visit the DHHS <a href="http://www.hhs.gov/web/social-media/policies/tos/" title="Terms of Service Agreements" target="_blank">Center for New Media</a>.</p>

        <p>For further information about privacy at NIH, email the <a href="mailto:privacy@mail.nih.gov" class="mailto">NIH Senior Official for Privacy<span class="mailto"><span class="element-invisible"> (link sends e-mail)</span></span></a>, call 301-451-3426 or visit&nbsp;the <a href="http://oma.od.nih.gov/public/MS/privacy/Pages/privacyact.aspx" target="_blank">NIH Office of Management Assessment</a>.</p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Privacy'
}
</script>
